### ISSUE TITLE
Print Receipt Adjustments

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#25]
Right now when we print the font is too big, so the receipt covers 2 pages.  

![image](https://cloud.githubusercontent.com/assets/629241/8156824/7153117a-1315-11e5-860c-20cb1ee64653.png)

We need to adjust the print CSS so that it will fit nicely on a single page.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
