### ISSUE TITLE
Option to email purchase receipt.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#26]
Add an option to the VT form so that users can email a copy of the receipt page to the billing address provided on the VT.

Also add an option in the config to enable/disable this by default.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
