### ISSUE TITLE
Error Display

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#27]
The error that displays if a failure occurs is very generic (on PayFlow that I just tested it simply says "Declined" and does not provide any error code or actual error message.)

Need to make sure quality error details are returned for DDP, PayFlow, and REST.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
