### ISSUE TITLE
Need better error handling with JSON response.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#28]
I have a user who was complaining that the solution simply wasn't working for them.  When I tested in Firebug I get this...

![image](https://cloud.githubusercontent.com/assets/629241/8861386/ccb38b78-314f-11e5-85e7-3bad2498add0.png)

The PHP warning about the log file path caused the JSON string to be invalid.  We need to handle that sort of thing better so the JSON string is always valid and can display any errors to the user instead of hiding it in Firebug.

**Comment by kcwebmedia** [comment]
This is due to missing logs directory path or write access missing for log directory. Turn logs off and the error is gone.

**We should add a check for the log directory before attempting to write to it. And we should show a warning at top of terminal html to let admin know logs will not work if not writeable**

**Comment by angelleye** [comment]
Right, that's what I explained to the user, but I still think we should be able to handle this better.  We should be able to trap any PHP errors that cause the JSON format to break and include them in the actual JSON format so that we can display them to the user.

The way it is now people just think it doesn't work because they don't see anything at all.

**Comment by kcwebmedia** [comment]
JSON responses are fine, php warning was causing this.

Added check for writable error log directory/file.
![image](https://cloud.githubusercontent.com/assets/7711293/19916315/e962e97e-a086-11e6-9931-d7b30d3038db.png)

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
