### ISSUE TITLE
Need better installation and usage instructions.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#29]
Need to update the Install.txt with better details.

**Comment by angelleye** [comment]
One specific thing is that we have instructions that load when the app loads, but until you rename config-sample and update the config file the app won't load so you can't see that step.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
