### ISSUE TITLE
Adjust field lengths...

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#31]
The email address field in the form seems to be getting truncated at 31 characters.  Need to make this larger to at least match what PayPal accepts.

User report:  https://www.angelleye.com/support/scp/tickets.php?id=434

**Comment by cturnersung** [comment]
The phone number fields also need adjustment to max length on input fields. Character limit needs to be 10 for Billing Phone Number and Shipping Phone Number.

Ref: Payflow doc: https://developer.paypal.com/docs/classic/payflow/integration-guide/

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
