### ISSUE TITLE
Typo in config file.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#32]
> Also just so you know [not as criticism; in fact your coding is impressive] on line 101-102 where your REST API credentials go, there is a typo that has confusion potential for those inexperienced with php. Is should be: test - live, test - live [but instead your placeholders show: test - live, live - live].

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
