### ISSUE TITLE
PayPal Partner Code Check

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#33]
Need to double check the PayPal Partner code (bn code) getting passed into the requests for each of these gateway options (ddp, payflow, rest).  

PayPal is telling me they aren't seeing volume that I'm expecting for them to be seeing from this tool.

**Comment by angelleye** [comment]
Looks like we included the unique code AngellEYE_SP_POS_VT in our REST implementation, but the other stuff is still just using our libraries default code of AngellEYE_PHPClass.

Need to setup a test I can run with REST to ensure PayPal is seeing those correctly.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
