### ISSUE TITLE
jQuery Bug..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#34]
Reported by user:  https://www.angelleye.com/support/scp/tickets.php?id=741

Using Firebug I was able to see that a jQuery syntax error is happening on the API result parsing, and I was able to reproduce this error:

![image](https://cloud.githubusercontent.com/assets/629241/19911259/747a410a-a060-11e6-9ea7-6053856d9702.png)

**Comment by angelleye** [comment]
Not sure if this is related or not, but it looks like when I run "bower update" there are lots of updates since we last did this.  

I did that in a separate local branch just to see what all it would bring in, but didn't resolve the issue.

**Comment by angelleye** [comment]
This is happening when logging is enabled in the config file, but the actual log file/path doesn't exist. 

We should be able to set the code so it will go ahead and create the log file for you instead of just failing.

**Comment by kcwebmedia** [comment]
Bower update would be another ticket. Not critical. Updating all bower components to newer versions would require testing time too.

**Comment by kcwebmedia** [comment]
This issue was covered within issue #28. Not Needed.
