### ISSUE TITLE
REST - Sandbox Flag

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-virtual-terminal-php#36]
It seems the $sandbox flag in the config file is not getting used with the REST integration, so everything is getting sent to the sandbox even when you try to run live transactions, which results in a client auth failure.

Need to update REST so that it looks at the $sandbox flag in the config file and reacts accordingly.

Need to follow up with this guy when this is done:  https://mail.google.com/mail/u/0/#inbox/15733951c9efa8f9

**Comment by kcwebmedia** [comment]
This needs more testing please. I believe sandbox endpoint will be used if $sandbox TRUE. But in the documentation PayPal gives for this it does not make it clear on when/where to utilize the 'mode'.
SEE doc (look at PHP example):
https://developer.paypal.com/docs/api/quickstart/environment/

**Comment by angelleye** [comment]
@kcwebmedia We have REST built into PayPal for WooCommerce and you can set sandbox vs. live mode there, so maybe you can see how it was done there..??

Maybe the same as this example.

**Comment by angelleye** [comment]
Yeah, I think we did it the same way:  https://www.angelleye.com/test-paypal-ipn/

```$this->mode``` is setting set with the sandbox settings.

**Comment by angelleye** [comment]
@kcwebmedia Notice that we're setting the PayPal Partner ID in that same config array that we're setting the live/sandbox mode value.  

It looks like you did that differently, though, here..??

**Comment by angelleye** [comment]
For example, you can see in the commit you made (below your changes) that we were using this to send the PayPal partner code:

```$paypal_rest->addRequestHeader('PayPal-Partner-Attribution-Id', 'AngellEYE_SP_POS_VT');```

And now you've added the setConfig() option to set the mode.  Do you know if we should be setting the partner ID there, too?

Now I'm worried that either this tool or our PayPal for WooCommerce plugin may be incorrect and not getting passed.

**Comment by kcwebmedia** [comment]
addRequestHeader and setConfig are two different things. I believe that everything is passed correctly on REST.

**Comment by devchristina2** [comment]
Hi @kcwebmedia,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
