### ISSUE TITLE
Error when use a MXN currency on REST

### ISSUE THREAD

**Issue by angelscabrerag** [angelleye/paypal-virtual-terminal-php#38]
Hi, 

when i config the var: $config['CurrencyCode'] to MXN value, the virtual terminal pos show the error:

<code>The following errors have occurred:
    Error:  VALIDATION_ERROR
    Message:  Invalid request. See details.
    Details:
        Field:  transactions[0].amount.currency
        Issue:  Value is not supported.
    Information Link:  https://developer.paypal.com/docs/api/payments/#errors
    Debug Id:  b6afee37d0302</code>

In the "config.php" file the var $config['CurrencyCode'] show only accept values: AUD, CAD, CZK, DKK, EUR, HKD, HUF, JPY, NOK, NZD, PLN, GBP, SGD, SEK, CHF, USD, but when go to check the Information Link:  https://developer.paypal.com/docs/api/payments/#errors, the info show MXN currency is supported and in the file "vendor/angelleye/paypal-php-library/src/angelleye/PayPal/PayPal.php" in the "CurrencyCodes" on line #461 MXN currency value is listed.

On USD currency works fine, but i need to use MXN currency.

So, can you help me to solve?

**Comment by angelleye** [comment]
Are you trying to setup REST?

**Comment by angelscabrerag** [comment]
Yes, im trying to use REST

**Comment by angelleye** [comment]
It looks like maybe the MXN currency code was added after we released this Virtual Terminal.  Are you familiar with Composer?  If you run "composer update" from the command line of your project it should pull it the latest version of the PayPal REST SDK, which could fix the issue for you.  

I've assigned this to one of our developers so we can get this done as part of this repo directly, but that may not happen until next week.

**Comment by angelscabrerag** [comment]
Thanks a lot for your response, im still learning composer so i will try to make the update. At any case i can wait one more week to get all working fine.

**Comment by angelscabrerag** [comment]
At this time i ran the `composer update` and the libraries updated correctly but when i tried on my web same error show up, so ran the composer command twice but not correct the issue.

composer update capture
![b446254fd00d5f39555a85536428f899](https://user-images.githubusercontent.com/9630621/34636838-cfd74cf6-f266-11e7-88bd-dc838d453e6e.png)

error capture
![screenshot-2018-1-5 paypal php virtual terminal pos](https://user-images.githubusercontent.com/9630621/34636848-07fef21e-f267-11e7-9aa3-780f530c5f57.png)

I think im wait for updates from you the next week.

**Comment by angelleye** [comment]
Just to be sure, did you upload all of the library files to your server after running the composer update?

**Comment by angelleye** [comment]
Also, is your PayPal account based in Mexico, or is it based in the US but you're just trying to process MXN currency?

**Comment by angelscabrerag** [comment]
1. I can confirm that i uploaded all files to my server and fill the `config.php` file again to be sure.
2. My PayPal account is based in Mexico, is for that i need to use the `MXN` currency.

**Comment by angelleye** [comment]
That could be the issue then.  REST credit card processing is only available in the US, and in fact they aren't even allowing new users to set it up anymore.  They're moving people to Braintree.  We still need to get Braintree added to this solution.  :(

**Comment by angelleye** [comment]
We're currently tied up on some existing projects, but I'd like to get this done within the the next few weeks.

**Comment by devchristina2** [comment]
Hi @angelscabrerag ,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
